---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-devspaces-to-ollama
  namespace: DEMO_NAMESPACE_PLACEHOLDER
spec:
  podSelector:
    matchLabels:
      app: AI_SERVICE_NAME_PLACEHOLDER
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/part-of: che.eclipse.org
      ports:
        - protocol: TCP
          port: 11434
